CREATE TABLE post (
  num INT(10) PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(50),
  contents VARCHAR(5000),
  writer VARCHAR(100), -- 필드 크기 조정
  w_date DATE DEFAULT NOW(),
  r_count INT(10) DEFAULT 0,
  c_count INT(10) DEFAULT 0
);

CREATE TABLE comments (
  c_num INT(10) PRIMARY KEY AUTO_INCREMENT,
  p_num INT(10),
  c_writer VARCHAR(50),
  c_contents VARCHAR(1000),
  CONSTRAINT dle FOREIGN KEY (p_num) REFERENCES post(num) ON DELETE CASCADE
);

DELETE FROM post;

DROP TABLE post;

DROP TABLE comments;

SELECT * FROM post;

SHOW VARIABLES LIKE 'character_set_database';

SHOW VARIABLES LIKE 'collation_database';

ALTER DATABASE mysql CHARACTER SET utf8mb4 COLLATE UTF8MB4_UNICODE_CI;

ALTER TABLE post CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE comments CONVERT TO CHARACTER SET utf8mb4 COLLATE UTF8MB4_UNICODE_CI;